SAMPLE_LINES = [
    "Hello, thank you for calling support, how can I help you today?",
    "Hi there, you've reached customer care, what can I do for you?",
    "Good morning, thanks for holding, how may I assist you?",
    "Good afternoon, this is Morgan speaking, how can I help?",
    "Hello, I'm Casey from customer support, what seems to be the issue?",
    "Thanks for calling, my name is Riley, how can I help you today?",
    "Hi, welcome back, I see you've called before, what's going on today?",
    "Hello, before we start, can I get your name please?",
    "Hi, I'll be happy to help you today, what's the issue?",
    "Good evening, thank you for your patience, how can I assist?",
    "Hi, I'm having trouble with my recent order, it hasn't arrived yet.",
    "My monitor stand arrived damaged, can you help?",
    "I ordered a webcam last week and it is missing a part.",
    "I'm calling about order 1896, the router won't turn on.",
    "There's a problem with my power bank, it keeps disconnecting.",
    "I need help, my tablet is the wrong item and I'm not sure what to do.",
    "This is frustrating, my smartwatch stopped working after a week again.",
    "I recently bought a printer and it has a cracked screen.",
    "Can someone help me, my vacuum cleaner won't charge?",
    "I'm not happy, the air fryer I ordered makes a strange noise.",
    "I'm sorry to hear that. Can you provide your order number?",
    "I understand, could you confirm the email used for the order?",
    "Let me pull that up, what's your order confirmation number?",
    "I apologize for the trouble. Can I get your account number please?",
    "Thanks for letting me know, do you have the order ID handy?",
    "I'm sorry about that, could you verify your shipping address?",
    "Let's get this sorted, can you tell me when you placed the order?",
    "I understand your frustration. What's the order number on the confirmation email?",
    "No problem, can you confirm your full name and order number?",
    "I hear you. Do you have the tracking number available?",
    "Sure, it's ORD-2071.",
    "Yes, the order number is 2867.",
    "It's 2013, placed on 25/10.",
    "The confirmation number is 2411.",
    "Here it is: 2564.",
    "My account number is ACC-1830.",
    "The tracking number is TRK-1838.",
    "I placed it on 11/09, order 2123.",
    "Let me check that for you, one moment please.",
    "Give me just a second to pull up your account.",
    "I'm looking into this right now.",
    "Let me check the technical support system for you.",
    "One moment, I'm reviewing the order details.",
    "I'm checking with our shipping team now.",
    "Let me verify this with our warehouse system.",
    "I'll need to escalate this to billing, one moment.",
    "Let me run a quick check on that office chair.",
    "I'm pulling up the shipment history now.",
    "I can see the order is currently in transit and should arrive within two days.",
    "I've issued a refund, it should reflect in 3-5 business days.",
    "I'm sending a replacement mechanical keyboard, it'll arrive within a week.",
    "I've escalated this to technical support, they'll follow up within 24 hours.",
    "I've applied a credit of $13.0 to your account.",
    "A technician will be dispatched to help resolve the router issue.",
    "I've updated your address, the power bank will ship there now.",
    "I've cancelled the order and refunded $57.5 to your original payment method.",
    "The smartwatch has been replaced under warranty at no cost to you.",
    "I've flagged this for our returns team to review further.",
    "Okay, thank you for checking.",
    "Is there anything else I can help you with today?",
    "No, that's all. Thanks for your help!",
    "You're welcome, have a great day!",
    "Thank you so much, that resolves my issue.",
    "Perfect, thank you for resolving this quickly.",
    "I appreciate your help, goodbye!",
    "Thanks again, that's everything for now.",
    "Great, thank you for your patience today.",
    "Is there a reference number for this call?",
    "I'd like to update my billing address, is that possible here?",
    "Of course, can you confirm the account holder's name for verification?",
    "It's under the name on the account, yes.",
    "Great, I've updated the address on file.",
    "My internet service has been down since this morning.",
    "I understand the frustration, let me run a diagnostic on the line.",
    "The diagnostic shows a fault upstream, a technician will be dispatched.",
    "When can I expect the technician to arrive?",
    "Between 2pm and 5pm tomorrow, you'll get a confirmation text.",
    "Can I speak to a supervisor about this?",
    "I'd like to cancel my subscription please.",
    "May I ask the reason for cancelling?",
    "The service didn't meet my expectations.",
    "I understand, I've processed the cancellation, no further charges will apply.",
    "Can you email me a confirmation of this cancellation?",
    "Absolutely, you'll receive that within the hour.",
    "I was charged twice for the same order, can you check?",
    "I see the duplicate charge, I'm refunding it right away.",
    "Thank you, how long will the refund take?",
    "Typically 3-5 business days depending on your bank.",
    "Good afternoon, this is Elena speaking, how can I help?",
    "Hello, I'm Noah from customer support, what seems to be the issue?",
    "Thanks for calling, my name is Maya, how can I help you today?",
    "Hi, I'm having trouble with my recent order, it is missing a part.",
    "My bluetooth speaker won't turn on, can you help?",
    "I ordered a fitness tracker last week and it keeps disconnecting.",
    "I'm calling about order 2279, the coffee maker is the wrong item.",
    "There's a problem with my office chair, it stopped working after a week.",
    "I need help, my desk lamp has a cracked screen and I'm not sure what to do.",
    "This is frustrating, my external hard drive won't charge again.",
    "I recently bought a gaming mouse and it makes a strange noise.",
    "Can someone help me, my mechanical keyboard hasn't arrived yet?",
    "I'm not happy, the monitor stand I ordered arrived damaged.",
    "Sure, it's ORD-1769.",
    "Yes, the order number is 2257.",
    "It's 1352, placed on 14/05.",
    "The confirmation number is 1266.",
    "Here it is: 2682.",
    "My account number is ACC-1042.",
    "The tracking number is TRK-1528.",
    "I placed it on 17/10, order 1097.",
    "Let me check the shipping system for you.",
    "I'm checking with our billing team now.",
    "I'll need to escalate this to returns, one moment.",
    "Let me run a quick check on that vacuum cleaner.",
    "I'm sending a replacement smartphone case, it'll arrive within a week.",
    "I've escalated this to shipping, they'll follow up within 24 hours.",
    "I've applied a credit of $50.5 to your account.",
    "A technician will be dispatched to help resolve the coffee maker issue.",
    "I've updated your address, the office chair will ship there now.",
    "I've cancelled the order and refunded $20.0 to your original payment method.",
    "The external hard drive has been replaced under warranty at no cost to you.",
    "I've flagged this for our account services team to review further.",
    "Good afternoon, this is Casey speaking, how can I help?",
    "Hello, I'm Riley from customer support, what seems to be the issue?",
    "Thanks for calling, my name is Sam, how can I help you today?",
    "Hi, I'm having trouble with my recent order, it arrived damaged.",
    "My webcam is missing a part, can you help?",
    "I ordered a router last week and it won't turn on.",
    "I'm calling about order 2249, the power bank keeps disconnecting.",
    "There's a problem with my tablet, it is the wrong item.",
    "I need help, my smartwatch stopped working after a week and I'm not sure what to do.",
    "This is frustrating, my printer has a cracked screen again.",
    "I recently bought a vacuum cleaner and it won't charge.",
    "Can someone help me, my smartphone case is missing a part?",
    "I'm not happy, the bluetooth speaker I ordered won't turn on.",
    "Sure, it's ORD-1770.",
    "Yes, the order number is 2147.",
    "It's 2834, placed on 13/04.",
    "The confirmation number is 2905.",
    "Here it is: 2065.",
    "My account number is ACC-2458.",
    "The tracking number is TRK-1997.",
    "I placed it on 26/04, order 1792.",
    "Let me check the billing system for you.",
    "I'm checking with our returns team now.",
    "I'll need to escalate this to account services, one moment.",
    "Let me run a quick check on that mechanical keyboard.",
    "I'm sending a replacement power bank, it'll arrive within a week.",
    "I've escalated this to billing, they'll follow up within 24 hours.",
    "I've applied a credit of $67.0 to your account.",
    "A technician will be dispatched to help resolve the printer issue.",
    "I've updated your address, the vacuum cleaner will ship there now.",
    "I've cancelled the order and refunded $63.0 to your original payment method.",
    "The wireless headphones has been replaced under warranty at no cost to you.",
    "I've flagged this for our technical support team to review further.",
    "Hi, I'm having trouble with my recent order, it won't turn on.",
    "My fitness tracker keeps disconnecting, can you help?",
    "I ordered a coffee maker last week and it is the wrong item.",
    "I'm calling about order 1738, the office chair stopped working after a week.",
    "There's a problem with my desk lamp, it has a cracked screen.",
    "I need help, my external hard drive won't charge and I'm not sure what to do.",
    "This is frustrating, my gaming mouse makes a strange noise again.",
    "I recently bought a mechanical keyboard and it hasn't arrived yet.",
    "Can someone help me, my monitor stand arrived damaged?",
    "I'm not happy, the webcam I ordered is missing a part.",
    "Sure, it's ORD-2143.",
    "Yes, the order number is 2432.",
    "It's 1083, placed on 27/08.",
    "The confirmation number is 2956.",
    "Here it is: 2581.",
    "My account number is ACC-2326.",
    "The tracking number is TRK-2023.",
    "I placed it on 09/05, order 1896.",
    "Let me check the returns system for you.",
    "I'm checking with our account services team now.",
    "I'll need to escalate this to technical support, one moment.",
    "Let me run a quick check on that smartphone case.",
    "I'm sending a replacement office chair, it'll arrive within a week.",
    "I've escalated this to returns, they'll follow up within 24 hours.",
    "I've applied a credit of $17.5 to your account.",
    "A technician will be dispatched to help resolve the gaming mouse issue.",
    "I've updated your address, the mechanical keyboard will ship there now.",
    "I've cancelled the order and refunded $31.5 to your original payment method.",
    "The webcam has been replaced under warranty at no cost to you.",
    "I've flagged this for our shipping team to review further.",
    "Hi, I'm having trouble with my recent order, it is the wrong item.",
    "My smartwatch stopped working after a week, can you help?",
    "I ordered a printer last week and it has a cracked screen.",
    "I'm calling about order 2523, the vacuum cleaner won't charge.",
    "There's a problem with my air fryer, it makes a strange noise.",
    "I need help, my wireless headphones hasn't arrived yet and I'm not sure what to do.",
    "This is frustrating, my laptop charger arrived damaged again.",
    "I recently bought a smartphone case and it is missing a part.",
    "Can someone help me, my bluetooth speaker won't turn on?",
    "I'm not happy, the fitness tracker I ordered keeps disconnecting.",
    "Sure, it's ORD-2032.",
    "Yes, the order number is 1926.",
    "It's 2171, placed on 12/02.",
    "The confirmation number is 2684.",
    "Here it is: 1122.",
    "My account number is ACC-2750.",
    "The tracking number is TRK-2505.",
    "I placed it on 11/02, order 2279.",
    "Let me check the account services system for you.",
    "I'm checking with our technical support team now.",
    "I'll need to escalate this to shipping, one moment.",
    "Let me run a quick check on that power bank.",
    "I'm sending a replacement vacuum cleaner, it'll arrive within a week.",
    "I've escalated this to account services, they'll follow up within 24 hours.",
    "I've applied a credit of $66.0 to your account.",
    "A technician will be dispatched to help resolve the laptop charger issue.",
    "I've updated your address, the smartphone case will ship there now.",
    "I've cancelled the order and refunded $44.0 to your original payment method.",
    "The fitness tracker has been replaced under warranty at no cost to you.",
    "I've flagged this for our billing team to review further.",
    "Hi, I'm having trouble with my recent order, it has a cracked screen.",
    "My external hard drive won't charge, can you help?",
    "I ordered a gaming mouse last week and it makes a strange noise.",
    "I'm calling about order 1354, the mechanical keyboard hasn't arrived yet.",
    "There's a problem with my monitor stand, it arrived damaged.",
    "I need help, my webcam is missing a part and I'm not sure what to do.",
    "This is frustrating, my router won't turn on again.",
    "I recently bought a power bank and it keeps disconnecting.",
    "Can someone help me, my tablet is the wrong item?",
    "I'm not happy, the smartwatch I ordered stopped working after a week.",
    "Sure, it's ORD-1987.",
    "Yes, the order number is 1767.",
    "It's 2749, placed on 12/11.",
    "The confirmation number is 2812.",
    "Here it is: 2359.",
    "My account number is ACC-2224.",
    "The tracking number is TRK-1132.",
    "I placed it on 23/01, order 2249.",
    "I've applied a credit of $53.5 to your account.",
    "I've cancelled the order and refunded $17.0 to your original payment method.",
    "Hi, I'm having trouble with my recent order, it makes a strange noise.",
    "My wireless headphones hasn't arrived yet, can you help?",
    "I ordered a laptop charger last week and it arrived damaged.",
    "I'm calling about order 1315, the smartphone case is missing a part.",
    "There's a problem with my bluetooth speaker, it won't turn on.",
    "I need help, my fitness tracker keeps disconnecting and I'm not sure what to do.",
    "This is frustrating, my coffee maker is the wrong item again.",
    "I recently bought a office chair and it stopped working after a week.",
    "Can someone help me, my desk lamp has a cracked screen?",
    "I'm not happy, the external hard drive I ordered won't charge.",
    "Sure, it's ORD-1855.",
    "Yes, the order number is 2937.",
    "It's 1183, placed on 17/03.",
    "The confirmation number is 1060.",
    "Here it is: 1573.",
    "My account number is ACC-1091.",
    "The tracking number is TRK-1068.",
    "I placed it on 19/05, order 1738.",
    "Let me run a quick check on that tablet.",
    "I'm sending a replacement air fryer, it'll arrive within a week.",
    "I've applied a credit of $64.0 to your account.",
    "A technician will be dispatched to help resolve the smartphone case issue.",
    "I've cancelled the order and refunded $48.0 to your original payment method.",
    "I'm calling about order 1276, the power bank keeps disconnecting.",
    "Can someone help me, my air fryer makes a strange noise?",
    "I'm not happy, the wireless headphones I ordered hasn't arrived yet.",
    "Sure, it's ORD-2959.",
    "Yes, the order number is 2885.",
    "It's 1874, placed on 03/05.",
    "The confirmation number is 2803.",
    "Here it is: 2066.",
    "My account number is ACC-2353.",
    "The tracking number is TRK-2246.",
    "I placed it on 19/06, order 2523.",
    "Let me run a quick check on that desk lamp.",
    "I'm sending a replacement monitor stand, it'll arrive within a week.",
    "I've applied a credit of $15.0 to your account.",
    "A technician will be dispatched to help resolve the power bank issue.",
    "I've updated your address, the tablet will ship there now.",
    "I've cancelled the order and refunded $29.0 to your original payment method.",
    "The printer has been replaced under warranty at no cost to you.",
    "I'm calling about order 2619, the office chair stopped working after a week.",
    "Sure, it's ORD-1731.",
    "Yes, the order number is 1253.",
    "It's 1964, placed on 08/01.",
    "The confirmation number is 1399.",
    "Here it is: 2797.",
    "My account number is ACC-2231.",
    "The tracking number is TRK-1251.",
    "I placed it on 21/12, order 1354.",
    "Let me run a quick check on that air fryer.",
    "I'm sending a replacement bluetooth speaker, it'll arrive within a week.",
    "I've applied a credit of $67.5 to your account.",
    "A technician will be dispatched to help resolve the office chair issue.",
    "I've updated your address, the desk lamp will ship there now.",
    "I've cancelled the order and refunded $23.0 to your original payment method.",
    "The gaming mouse has been replaced under warranty at no cost to you.",
    "I'm calling about order 1701, the vacuum cleaner won't charge.",
    "Sure, it's ORD-2621.",
    "Yes, the order number is 2925.",
    "It's 2987, placed on 26/01.",
    "The confirmation number is 2389.",
    "Here it is: 1422.",
    "My account number is ACC-1264.",
    "The tracking number is TRK-1172.",
    "I placed it on 24/06, order 1315.",
    "Let me run a quick check on that monitor stand.",
    "I'm sending a replacement tablet, it'll arrive within a week.",
    "I've applied a credit of $10.0 to your account.",
    "A technician will be dispatched to help resolve the vacuum cleaner issue.",
    "I've updated your address, the air fryer will ship there now.",
    "I've cancelled the order and refunded $39.5 to your original payment method.",
    "The laptop charger has been replaced under warranty at no cost to you.",
    "I'm calling about order 2071, the mechanical keyboard hasn't arrived yet.",
    "Sure, it's ORD-2715.",
    "Yes, the order number is 2675.",
    "It's 2892, placed on 01/03.",
    "The confirmation number is 1137.",
    "Here it is: 1215.",
    "My account number is ACC-2160.",
    "The tracking number is TRK-1027.",
    "I placed it on 18/12, order 1276.",
    "Let me run a quick check on that bluetooth speaker.",
    "I'm sending a replacement desk lamp, it'll arrive within a week.",
    "I've applied a credit of $12.0 to your account.",
    "A technician will be dispatched to help resolve the mechanical keyboard issue.",
    "I've updated your address, the monitor stand will ship there now.",
    "I've cancelled the order and refunded $32.5 to your original payment method.",
    "The router has been replaced under warranty at no cost to you.",
    "I'm calling about order 1769, the smartphone case is missing a part.",
    "Sure, it's ORD-1342.",
    "Yes, the order number is 2672.",
    "It's 2796, placed on 02/02.",
    "The confirmation number is 1802.",
    "Here it is: 1827.",
    "My account number is ACC-2293.",
    "The tracking number is TRK-2668.",
    "I placed it on 05/02, order 2619.",
    "I've applied a credit of $25.5 to your account.",
    "I've updated your address, the bluetooth speaker will ship there now.",
    "I've cancelled the order and refunded $49.0 to your original payment method.",
    "The coffee maker has been replaced under warranty at no cost to you.",
    "Good afternoon, this is Riley speaking, how can I help?",
    "Hello, I'm Sam from customer support, what seems to be the issue?",
    "Thanks for calling, my name is Jamie, how can I help you today?",
    "Hi, I'm having trouble with my recent order, it won't charge.",
    "I'm calling about order 1770, the power bank keeps disconnecting.",
    "Sure, it's ORD-2867.",
    "Yes, the order number is 2013.",
    "It's 2411, placed on 11/05.",
    "The confirmation number is 2564.",
    "Here it is: 1830.",
    "My account number is ACC-1838.",
    "The tracking number is TRK-2123.",
    "I placed it on 05/01, order 1701.",
    "I've applied a credit of $47.0 to your account.",
    "I've cancelled the order and refunded $35.5 to your original payment method.",
    "Good afternoon, this is Noah speaking, how can I help?",
    "Hello, I'm Maya from customer support, what seems to be the issue?",
    "Thanks for calling, my name is Liam, how can I help you today?",
    "My laptop charger arrived damaged, can you help?",
    "I ordered a smartphone case last week and it is missing a part.",
    "I'm calling about order 2114, the bluetooth speaker won't turn on.",
    "There's a problem with my fitness tracker, it keeps disconnecting.",
    "I need help, my coffee maker is the wrong item and I'm not sure what to do.",
    "This is frustrating, my office chair stopped working after a week again.",
    "I recently bought a desk lamp and it has a cracked screen.",
    "Can someone help me, my external hard drive won't charge?",
    "I'm not happy, the gaming mouse I ordered makes a strange noise.",
    "Sure, it's ORD-2257.",
    "Yes, the order number is 1352.",
    "It's 1266, placed on 10/10.",
    "The confirmation number is 2682.",
    "Here it is: 1042.",
    "My account number is ACC-1528.",
    "The tracking number is TRK-1097.",
    "I placed it on 15/05, order 2071.",
    "I've applied a credit of $58.5 to your account.",
    "I've cancelled the order and refunded $21.0 to your original payment method.",
    "My router won't turn on, can you help?",
    "I ordered a power bank last week and it keeps disconnecting.",
    "I'm calling about order 2032, the tablet is the wrong item.",
    "There's a problem with my smartwatch, it stopped working after a week.",
    "I need help, my printer has a cracked screen and I'm not sure what to do.",
    "This is frustrating, my vacuum cleaner won't charge again.",
    "I recently bought a air fryer and it makes a strange noise.",
    "Can someone help me, my wireless headphones hasn't arrived yet?",
    "I'm not happy, the laptop charger I ordered arrived damaged.",
    "Sure, it's ORD-2147.",
    "Yes, the order number is 2834.",
    "It's 2905, placed on 22/11.",
    "The confirmation number is 2065.",
    "Here it is: 2458.",
    "My account number is ACC-1997.",
    "The tracking number is TRK-1792.",
    "I placed it on 06/03, order 1769.",
    "I've applied a credit of $30.5 to your account.",
    "I've cancelled the order and refunded $66.5 to your original payment method.",
    "Hi, I'm having trouble with my recent order, it keeps disconnecting.",
    "My coffee maker is the wrong item, can you help?",
    "I ordered a office chair last week and it stopped working after a week.",
    "I'm calling about order 1987, the desk lamp has a cracked screen.",
    "There's a problem with my external hard drive, it won't charge.",
    "I need help, my gaming mouse makes a strange noise and I'm not sure what to do.",
    "This is frustrating, my mechanical keyboard hasn't arrived yet again.",
    "I recently bought a monitor stand and it arrived damaged.",
    "Can someone help me, my webcam is missing a part?",
    "I'm not happy, the router I ordered won't turn on.",
    "Sure, it's ORD-2001.",
    "Yes, the order number is 1196.",
    "It's 2406, placed on 17/04.",
    "The confirmation number is 2914.",
    "Here it is: 2331.",
    "My account number is ACC-1463.",
    "The tracking number is TRK-2183.",
    "I placed it on 01/12, order 1401.",
    "I've applied a credit of $49.5 to your account.",
    "I've cancelled the order and refunded $24.0 to your original payment method.",
    "Hi, I'm having trouble with my recent order, it stopped working after a week.",
    "My printer has a cracked screen, can you help?",
    "I ordered a vacuum cleaner last week and it won't charge.",
    "I'm calling about order 1855, the air fryer makes a strange noise.",
    "There's a problem with my wireless headphones, it hasn't arrived yet.",
    "I need help, my laptop charger arrived damaged and I'm not sure what to do.",
    "This is frustrating, my smartphone case is missing a part again.",
    "I recently bought a bluetooth speaker and it won't turn on.",
    "Can someone help me, my fitness tracker keeps disconnecting?",
    "I'm not happy, the coffee maker I ordered is the wrong item.",
    "Sure, it's ORD-1926.",
    "Yes, the order number is 2171.",
    "It's 2684, placed on 12/09.",
    "The confirmation number is 1122.",
    "Here it is: 2750.",
    "My account number is ACC-1527.",
    "The tracking number is TRK-2600.",
    "I placed it on 05/05, order 2114.",
    "Let me run a quick check on that webcam.",
    "I've applied a credit of $63.5 to your account.",
    "I've cancelled the order and refunded $22.5 to your original payment method.",
    "My gaming mouse makes a strange noise, can you help?",
    "I ordered a mechanical keyboard last week and it hasn't arrived yet.",
    "I'm calling about order 2959, the monitor stand arrived damaged.",
    "There's a problem with my webcam, it is missing a part.",
    "I need help, my router won't turn on and I'm not sure what to do.",
    "This is frustrating, my power bank keeps disconnecting again.",
    "I recently bought a tablet and it is the wrong item.",
    "Can someone help me, my smartwatch stopped working after a week?",
    "I'm not happy, the printer I ordered has a cracked screen.",
    "Sure, it's ORD-1767.",
    "Yes, the order number is 2749.",
    "It's 2812, placed on 14/01.",
    "The confirmation number is 2359.",
    "Here it is: 2224.",
    "My account number is ACC-1132.",
    "The tracking number is TRK-2249.",
    "I placed it on 16/10, order 2032.",
    "Let me run a quick check on that fitness tracker.",
    "I'm sending a replacement external hard drive, it'll arrive within a week.",
    "I've applied a credit of $25.0 to your account.",
    "A technician will be dispatched to help resolve the monitor stand issue.",
    "I've updated your address, the webcam will ship there now.",
    "I've cancelled the order and refunded $64.5 to your original payment method.",
    "I'm calling about order 1731, the bluetooth speaker won't turn on.",
    "Sure, it's ORD-2937.",
    "Yes, the order number is 1183.",
    "It's 1060, placed on 06/05.",
    "The confirmation number is 1573.",
    "Here it is: 1091.",
    "My account number is ACC-1068.",
    "The tracking number is TRK-1738.",
    "I placed it on 12/07, order 1987.",
    "Let me run a quick check on that smartwatch.",
    "I'm sending a replacement wireless headphones, it'll arrive within a week.",
    "I've applied a credit of $58.0 to your account.",
    "A technician will be dispatched to help resolve the bluetooth speaker issue.",
    "I've updated your address, the fitness tracker will ship there now.",
    "I've cancelled the order and refunded $55.5 to your original payment method.",
    "The office chair has been replaced under warranty at no cost to you.",
    "I'm calling about order 2621, the tablet is the wrong item.",
    "Sure, it's ORD-2885.",
    "Yes, the order number is 1874.",
    "It's 2803, placed on 04/06.",
    "The confirmation number is 2066.",
    "Here it is: 2353.",
    "My account number is ACC-2246.",
    "The tracking number is TRK-2523.",
    "I placed it on 09/12, order 1855.",
    "Let me run a quick check on that external hard drive.",
    "I'm sending a replacement webcam, it'll arrive within a week.",
    "I've applied a credit of $10.5 to your account.",
    "A technician will be dispatched to help resolve the tablet issue.",
    "I've updated your address, the smartwatch will ship there now.",
    "I've cancelled the order and refunded $59.5 to your original payment method.",
    "The vacuum cleaner has been replaced under warranty at no cost to you.",
    "I'm calling about order 2715, the desk lamp has a cracked screen.",
    "Sure, it's ORD-1253.",
    "Yes, the order number is 1964.",
    "It's 1399, placed on 14/12.",
    "The confirmation number is 2797.",
    "Here it is: 2231.",
    "My account number is ACC-1251.",
    "The tracking number is TRK-1354.",
    "I placed it on 07/08, order 2959.",
    "Let me run a quick check on that wireless headphones.",
    "I'm sending a replacement fitness tracker, it'll arrive within a week.",
    "I've applied a credit of $32.0 to your account.",
    "A technician will be dispatched to help resolve the desk lamp issue.",
    "I've updated your address, the external hard drive will ship there now.",
    "I've cancelled the order and refunded $24.5 to your original payment method.",
    "The mechanical keyboard has been replaced under warranty at no cost to you.",
    "I'm calling about order 1342, the air fryer makes a strange noise.",
    "Sure, it's ORD-2925.",
    "Yes, the order number is 2987.",
    "It's 2389, placed on 22/09.",
    "The confirmation number is 1422.",
    "Here it is: 1264.",
    "My account number is ACC-1172.",
    "The tracking number is TRK-1315.",
    "I placed it on 25/12, order 1731.",
    "I'm sending a replacement smartwatch, it'll arrive within a week.",
    "I've applied a credit of $43.5 to your account.",
    "A technician will be dispatched to help resolve the air fryer issue.",
    "I've updated your address, the wireless headphones will ship there now.",
    "I've cancelled the order and refunded $47.5 to your original payment method.",
    "The smartphone case has been replaced under warranty at no cost to you.",
    "Good afternoon, this is Sam speaking, how can I help?",
    "I'm calling about order 2867, the monitor stand arrived damaged.",
    "Sure, it's ORD-2675.",
    "Yes, the order number is 2892.",
    "It's 1137, placed on 12/06.",
    "The confirmation number is 1215.",
    "Here it is: 2160.",
    "My account number is ACC-1027.",
    "The tracking number is TRK-1276.",
    "I placed it on 28/11, order 2621.",
    "I've applied a credit of $45.5 to your account.",
    "I've cancelled the order and refunded $26.0 to your original payment method.",
    "The power bank has been replaced under warranty at no cost to you.",
    "Good afternoon, this is Maya speaking, how can I help?",
    "Hello, I'm Liam from customer support, what seems to be the issue?",
    "Thanks for calling, my name is Alex, how can I help you today?",
    "My vacuum cleaner won't charge, can you help?",
    "I ordered a air fryer last week and it makes a strange noise.",
    "I'm calling about order 2257, the bluetooth speaker won't turn on.",
    "Sure, it's ORD-2672.",
    "Yes, the order number is 2796.",
    "It's 1802, placed on 04/10.",
    "The confirmation number is 1827.",
    "Here it is: 2293.",
    "My account number is ACC-2668.",
    "The tracking number is TRK-2619.",
    "I placed it on 01/06, order 2715.",
    "I've applied a credit of $42.5 to your account.",
    "I've cancelled the order and refunded $44.5 to your original payment method.",
    "Hello, I'm Jamie from customer support, what seems to be the issue?",
    "Thanks for calling, my name is Priya, how can I help you today?",
    "My mechanical keyboard hasn't arrived yet, can you help?",
    "I ordered a monitor stand last week and it arrived damaged.",
    "I'm calling about order 2363, the webcam is missing a part.",
    "There's a problem with my router, it won't turn on.",
    "I need help, my power bank keeps disconnecting and I'm not sure what to do.",
    "This is frustrating, my tablet is the wrong item again.",
    "I recently bought a smartwatch and it stopped working after a week.",
    "Can someone help me, my printer has a cracked screen?",
    "I'm not happy, the vacuum cleaner I ordered won't charge.",
    "Sure, it's ORD-2013.",
    "Yes, the order number is 2411.",
    "It's 2564, placed on 16/08.",
    "The confirmation number is 1830.",
    "Here it is: 1838.",
    "My account number is ACC-2123.",
    "The tracking number is TRK-1701.",
    "I placed it on 19/09, order 1342.",
    "I've applied a credit of $31.0 to your account.",
    "I've cancelled the order and refunded $53.0 to your original payment method.",
    "My smartphone case is missing a part, can you help?",
    "I ordered a bluetooth speaker last week and it won't turn on.",
    "I'm calling about order 2001, the fitness tracker keeps disconnecting.",
    "There's a problem with my coffee maker, it is the wrong item.",
    "I need help, my office chair stopped working after a week and I'm not sure what to do.",
    "This is frustrating, my desk lamp has a cracked screen again.",
    "I recently bought a external hard drive and it won't charge.",
    "Can someone help me, my gaming mouse makes a strange noise?",
    "I'm not happy, the mechanical keyboard I ordered hasn't arrived yet.",
    "Sure, it's ORD-2580.",
    "Yes, the order number is 1266.",
    "It's 2682, placed on 25/03.",
    "The confirmation number is 1042.",
    "Here it is: 1528.",
    "My account number is ACC-1097.",
    "The tracking number is TRK-2071.",
    "I placed it on 09/09, order 2867.",
    "I've applied a credit of $54.5 to your account.",
    "I've cancelled the order and refunded $22.0 to your original payment method.",
    "My power bank keeps disconnecting, can you help?",
    "I ordered a tablet last week and it is the wrong item.",
    "I'm calling about order 1926, the smartwatch stopped working after a week.",
    "There's a problem with my printer, it has a cracked screen.",
    "I need help, my vacuum cleaner won't charge and I'm not sure what to do.",
    "This is frustrating, my air fryer makes a strange noise again.",
    "I recently bought a wireless headphones and it hasn't arrived yet.",
    "Can someone help me, my laptop charger arrived damaged?",
    "I'm not happy, the smartphone case I ordered is missing a part.",
    "Sure, it's ORD-1067.",
    "Yes, the order number is 2677.",
    "It's 1368, placed on 22/01.",
    "The confirmation number is 2942.",
    "Here it is: 1069.",
    "My account number is ACC-1819.",
    "The tracking number is TRK-2163.",
    "I placed it on 20/01, order 2376.",
    "I've applied a credit of $56.5 to your account.",
    "I've cancelled the order and refunded $40.0 to your original payment method.",
    "My office chair stopped working after a week, can you help?",
    "I ordered a desk lamp last week and it has a cracked screen.",
    "I'm calling about order 1767, the external hard drive won't charge.",
    "There's a problem with my gaming mouse, it makes a strange noise.",
    "I need help, my mechanical keyboard hasn't arrived yet and I'm not sure what to do.",
    "This is frustrating, my monitor stand arrived damaged again.",
    "I recently bought a webcam and it is missing a part.",
    "Can someone help me, my router won't turn on?",
    "I'm not happy, the power bank I ordered keeps disconnecting.",
    "Sure, it's ORD-1196.",
    "Yes, the order number is 2406.",
    "It's 2914, placed on 08/08.",
    "The confirmation number is 2331.",
    "Here it is: 1463.",
    "My account number is ACC-2183.",
    "The tracking number is TRK-1401.",
    "I placed it on 28/09, order 2363.",
    "Let me run a quick check on that laptop charger.",
    "I've applied a credit of $19.0 to your account.",
    "I've cancelled the order and refunded $54.0 to your original payment method.",
    "I'm calling about order 2937, the wireless headphones hasn't arrived yet.",
    "There's a problem with my laptop charger, it arrived damaged.",
    "I need help, my smartphone case is missing a part and I'm not sure what to do.",
    "This is frustrating, my bluetooth speaker won't turn on again.",
    "I recently bought a fitness tracker and it keeps disconnecting.",
    "Can someone help me, my coffee maker is the wrong item?",
    "I'm not happy, the office chair I ordered stopped working after a week.",
    "Sure, it's ORD-2171.",
    "Yes, the order number is 2684.",
    "It's 1122, placed on 01/10.",
    "The confirmation number is 2750.",
    "Here it is: 1527.",
    "My account number is ACC-2600.",
    "The tracking number is TRK-2114.",
    "I placed it on 13/09, order 2001.",
    "Let me run a quick check on that router.",
    "I'm sending a replacement printer, it'll arrive within a week.",
    "I've applied a credit of $62.0 to your account.",
    "A technician will be dispatched to help resolve the wireless headphones issue.",
    "I've updated your address, the laptop charger will ship there now.",
    "I've cancelled the order and refunded $26.5 to your original payment method.",
    "The bluetooth speaker has been replaced under warranty at no cost to you.",
    "I'm calling about order 2885, the webcam is missing a part.",
    "Sure, it's ORD-2749.",
    "Yes, the order number is 2812.",
    "It's 2359, placed on 13/08.",
    "The confirmation number is 2224.",
    "Here it is: 1132.",
    "My account number is ACC-2249.",
    "The tracking number is TRK-2032.",
    "I placed it on 19/10, order 1926.",
    "Let me run a quick check on that coffee maker.",
    "I'm sending a replacement gaming mouse, it'll arrive within a week.",
    "I've applied a credit of $36.0 to your account.",
    "A technician will be dispatched to help resolve the webcam issue.",
    "I've updated your address, the router will ship there now.",
    "I've cancelled the order and refunded $34.0 to your original payment method.",
    "The tablet has been replaced under warranty at no cost to you.",
    "I'm calling about order 1253, the fitness tracker keeps disconnecting.",
    "Sure, it's ORD-1183.",
    "Yes, the order number is 1060.",
    "It's 1573, placed on 05/08.",
    "The confirmation number is 1091.",
    "Here it is: 1068.",
    "My account number is ACC-1738.",
    "The tracking number is TRK-1987.",
    "I placed it on 28/03, order 1767.",
    "Let me run a quick check on that printer.",
    "I'm sending a replacement laptop charger, it'll arrive within a week.",
    "I've applied a credit of $21.5 to your account.",
    "A technician will be dispatched to help resolve the fitness tracker issue.",
    "I've updated your address, the coffee maker will ship there now.",
    "I've cancelled the order and refunded $46.0 to your original payment method.",
    "The desk lamp has been replaced under warranty at no cost to you.",
    "I'm calling about order 2925, the smartwatch stopped working after a week.",
    "Sure, it's ORD-1874.",
    "Yes, the order number is 2803.",
    "It's 2066, placed on 19/08.",
    "The confirmation number is 2353.",
    "Here it is: 2246.",
    "My account number is ACC-2523.",
    "The tracking number is TRK-1855.",
    "I placed it on 02/04, order 2937.",
    "Let me run a quick check on that gaming mouse.",
    "I'm sending a replacement router, it'll arrive within a week.",
    "I've applied a credit of $60.5 to your account.",
    "A technician will be dispatched to help resolve the smartwatch issue.",
    "I've updated your address, the printer will ship there now.",
    "I've cancelled the order and refunded $39.0 to your original payment method.",
    "The air fryer has been replaced under warranty at no cost to you.",
    "I'm calling about order 2675, the external hard drive won't charge.",
    "Sure, it's ORD-1964.",
    "Yes, the order number is 1399.",
    "It's 2797, placed on 03/02.",
    "The confirmation number is 2231.",
    "Here it is: 1251.",
    "My account number is ACC-1354.",
    "The tracking number is TRK-2959.",
    "I placed it on 18/04, order 2885.",
    "I'm sending a replacement coffee maker, it'll arrive within a week.",
    "I've applied a credit of $46.5 to your account.",
    "A technician will be dispatched to help resolve the external hard drive issue.",
    "I've updated your address, the gaming mouse will ship there now.",
    "I've cancelled the order and refunded $38.5 to your original payment method.",
    "The monitor stand has been replaced under warranty at no cost to you.",
    "Good afternoon, this is Liam speaking, how can I help?",
    "Hello, I'm Alex from customer support, what seems to be the issue?",
    "Thanks for calling, my name is Jordan, how can I help you today?",
    "I'm calling about order 2672, the wireless headphones hasn't arrived yet.",
    "Sure, it's ORD-2987.",
    "Yes, the order number is 2389.",
    "It's 1422, placed on 04/02.",
    "The confirmation number is 1264.",
    "Here it is: 1172.",
    "My account number is ACC-1315.",
    "The tracking number is TRK-1731.",
    "I placed it on 07/06, order 1253.",
    "I've applied a credit of $51.0 to your account.",
    "I've cancelled the order and refunded $57.0 to your original payment method.",
    "Good afternoon, this is Jamie speaking, how can I help?",
    "Hello, I'm Priya from customer support, what seems to be the issue?",
    "Thanks for calling, my name is Wei, how can I help you today?",
    "My desk lamp has a cracked screen, can you help?",
    "I ordered a external hard drive last week and it won't charge.",
    "I'm calling about order 1787, the gaming mouse makes a strange noise.",
    "There's a problem with my mechanical keyboard, it hasn't arrived yet.",
    "Sure, it's ORD-2892.",
    "Yes, the order number is 1137.",
    "It's 1215, placed on 12/03.",
    "The confirmation number is 2160.",
    "Here it is: 1027.",
    "My account number is ACC-1276.",
    "The tracking number is TRK-2621.",
    "I placed it on 19/01, order 2925.",
    "I've applied a credit of $35.0 to your account.",
    "I've cancelled the order and refunded $18.0 to your original payment method.",
    "My air fryer makes a strange noise, can you help?",
    "I ordered a wireless headphones last week and it hasn't arrived yet.",
    "I'm calling about order 2580, the laptop charger arrived damaged.",
    "There's a problem with my smartphone case, it is missing a part.",
    "I need help, my bluetooth speaker won't turn on and I'm not sure what to do.",
    "This is frustrating, my fitness tracker keeps disconnecting again.",
    "I recently bought a coffee maker and it is the wrong item.",
    "Can someone help me, my office chair stopped working after a week?",
    "I'm not happy, the desk lamp I ordered has a cracked screen.",
    "Sure, it's ORD-2796.",
    "Yes, the order number is 1802.",
    "It's 1827, placed on 06/06.",
    "The confirmation number is 2293.",
    "Here it is: 2668.",
    "My account number is ACC-2619.",
    "The tracking number is TRK-2715.",
    "I placed it on 01/02, order 2675.",
    "I've applied a credit of $14.0 to your account.",
    "I've cancelled the order and refunded $61.0 to your original payment method.",
    "I'm calling about order 1067, the router won't turn on.",
    "Sure, it's ORD-1187.",
    "Yes, the order number is 1547.",
    "It's 2623, placed on 12/10.",
    "The confirmation number is 1838.",
    "Here it is: 2123.",
    "My account number is ACC-1701.",
    "The tracking number is TRK-1342.",
    "I placed it on 07/01, order 2672.",
    "I've applied a credit of $57.5 to your account.",
    "I've cancelled the order and refunded $27.0 to your original payment method.",
    "I'm calling about order 1196, the coffee maker is the wrong item.",
    "Sure, it's ORD-1591.",
    "Yes, the order number is 2031.",
    "It's 1426, placed on 13/10.",
    "The confirmation number is 2419.",
    "Here it is: 1708.",
    "My account number is ACC-1759.",
    "The tracking number is TRK-2904.",
    "I placed it on 05/10, order 1787.",
    "I've applied a credit of $20.0 to your account.",
    "I've cancelled the order and refunded $43.0 to your original payment method.",
    "My tablet is the wrong item, can you help?",
    "I ordered a smartwatch last week and it stopped working after a week.",
    "I'm calling about order 2171, the printer has a cracked screen.",
    "There's a problem with my vacuum cleaner, it won't charge.",
    "I need help, my air fryer makes a strange noise and I'm not sure what to do.",
    "This is frustrating, my wireless headphones hasn't arrived yet again.",
    "I recently bought a laptop charger and it arrived damaged.",
    "Sure, it's ORD-2677.",
    "Yes, the order number is 1368.",
    "It's 2942, placed on 05/12.",
    "The confirmation number is 1069.",
    "Here it is: 1819.",
    "My account number is ACC-2163.",
    "The tracking number is TRK-2376.",
    "I placed it on 01/04, order 2580.",
    "I've applied a credit of $63.0 to your account.",
    "I've cancelled the order and refunded $28.5 to your original payment method.",
    "I'm calling about order 2749, the gaming mouse makes a strange noise.",
    "I need help, my monitor stand arrived damaged and I'm not sure what to do.",
    "This is frustrating, my webcam is missing a part again.",
    "I recently bought a router and it won't turn on.",
    "Can someone help me, my power bank keeps disconnecting?",
    "I'm not happy, the tablet I ordered is the wrong item.",
    "Sure, it's ORD-2406.",
    "Yes, the order number is 2914.",
    "It's 2331, placed on 05/03.",
    "The confirmation number is 1463.",
    "Here it is: 2183.",
    "My account number is ACC-1401.",
    "The tracking number is TRK-2363.",
    "I placed it on 12/05, order 1067.",
    "I've applied a credit of $52.5 to your account.",
    "I've cancelled the order and refunded $53.5 to your original payment method.",
    "I'm calling about order 1183, the laptop charger arrived damaged.",
    "Sure, it's ORD-2684.",
    "Yes, the order number is 1122.",
    "It's 2750, placed on 10/11.",
    "The confirmation number is 1527.",
    "Here it is: 2600.",
    "My account number is ACC-2114.",
    "The tracking number is TRK-2001.",
    "I placed it on 06/02, order 1196.",
    "I've applied a credit of $16.5 to your account.",
    "I've cancelled the order and refunded $55.0 to your original payment method.",
    "I'm calling about order 1874, the router won't turn on.",
    "Sure, it's ORD-2812.",
    "Yes, the order number is 2359.",
    "It's 2224, placed on 08/04.",
    "The confirmation number is 1132.",
    "Here it is: 2249.",
    "My account number is ACC-2032.",
    "The tracking number is TRK-1926.",
    "I placed it on 12/02, order 2171.",
    "I've applied a credit of $48.5 to your account.",
    "I've cancelled the order and refunded $28.0 to your original payment method.",
    "I'm calling about order 1964, the coffee maker is the wrong item.",
    "Sure, it's ORD-1060.",
    "Yes, the order number is 1573.",
    "It's 1091, placed on 18/08.",
    "The confirmation number is 1068.",
    "Here it is: 1738.",
    "My account number is ACC-1987.",
    "The tracking number is TRK-1767.",
    "I placed it on 12/11, order 2749.",
    "I've applied a credit of $29.5 to your account.",
    "I've cancelled the order and refunded $30.0 to your original payment method.",
    "I'm calling about order 2987, the printer has a cracked screen.",
    "Sure, it's ORD-2803.",
    "Yes, the order number is 2066.",
    "It's 2353, placed on 20/08.",
    "The confirmation number is 2246.",
    "Here it is: 2523.",
    "My account number is ACC-1855.",
    "The tracking number is TRK-2937.",
    "I placed it on 17/03, order 1183.",
    "I've applied a credit of $29.0 to your account.",
    "I've cancelled the order and refunded $42.0 to your original payment method.",
    "Good afternoon, this is Priya speaking, how can I help?",
    "Hello, I'm Wei from customer support, what seems to be the issue?",
    "Thanks for calling, my name is Fatima, how can I help you today?",
    "I'm calling about order 2892, the gaming mouse makes a strange noise.",
    "Sure, it's ORD-1399.",
    "Yes, the order number is 2797.",
    "It's 2231, placed on 16/06.",
    "The confirmation number is 1251.",
    "Here it is: 1354.",
    "My account number is ACC-2959.",
    "The tracking number is TRK-2885.",
    "I placed it on 03/05, order 1874.",
    "I've applied a credit of $23.0 to your account.",
    "I've cancelled the order and refunded $41.5 to your original payment method.",
    "Good afternoon, this is Alex speaking, how can I help?",
    "Hello, I'm Jordan from customer support, what seems to be the issue?",
    "Thanks for calling, my name is Taylor, how can I help you today?",
    "I'm calling about order 2545, the vacuum cleaner won't charge.",
    "Sure, it's ORD-2389.",
    "Yes, the order number is 1422.",
    "It's 1264, placed on 28/10.",
    "The confirmation number is 1172.",
    "Here it is: 1315.",
    "My account number is ACC-1731.",
    "The tracking number is TRK-1253.",
    "I placed it on 08/01, order 1964.",
    "I've applied a credit of $39.5 to your account.",
    "I've cancelled the order and refunded $27.5 to your original payment method.",
    "I'm calling about order 1187, the mechanical keyboard hasn't arrived yet.",
    "Sure, it's ORD-1137.",
    "Yes, the order number is 1215.",
    "It's 2160, placed on 09/01.",
    "The confirmation number is 1027.",
    "Here it is: 1276.",
    "My account number is ACC-2621.",
    "The tracking number is TRK-2925.",
    "I placed it on 26/01, order 2987.",
    "I've applied a credit of $32.5 to your account.",
    "I've cancelled the order and refunded $37.0 to your original payment method.",
    "I'm calling about order 1591, the smartphone case is missing a part.",
    "Sure, it's ORD-2949.",
    "Yes, the order number is 2495.",
    "It's 1032, placed on 04/09.",
    "The confirmation number is 2258.",
    "Here it is: 2832.",
    "My account number is ACC-2715.",
    "The tracking number is TRK-2675.",
    "I placed it on 01/03, order 2892.",
    "I've applied a credit of $49.0 to your account.",
    "I've cancelled the order and refunded $51.5 to your original payment method.",
    "I'm calling about order 2677, the power bank keeps disconnecting.",
    "Sure, it's ORD-1547.",
    "Yes, the order number is 2623.",
    "It's 1971, placed on 17/01.",
    "The confirmation number is 2275.",
    "Here it is: 2634.",
    "My account number is ACC-2291.",
    "The tracking number is TRK-2037.",
    "I placed it on 07/10, order 2545.",
    "I've applied a credit of $35.5 to your account.",
    "I've cancelled the order and refunded $33.5 to your original payment method.",
    "I'm calling about order 2406, the office chair stopped working after a week.",
    "Sure, it's ORD-2031.",
    "Yes, the order number is 1426.",
    "It's 2419, placed on 26/09.",
    "The confirmation number is 1708.",
    "Here it is: 1759.",
    "My account number is ACC-2904.",
    "The tracking number is TRK-1787.",
    "I placed it on 11/11, order 1187.",
    "I've applied a credit of $14.5 to your account.",
    "I've cancelled the order and refunded $13.5 to your original payment method.",
    "I'm calling about order 2684, the vacuum cleaner won't charge.",
    "Sure, it's ORD-1368.",
    "Yes, the order number is 2942.",
    "It's 1069, placed on 26/10.",
    "The confirmation number is 1819.",
    "Here it is: 2163.",
    "My account number is ACC-2376.",
    "The tracking number is TRK-2580.",
    "I placed it on 26/07, order 1591.",
    "I've applied a credit of $40.5 to your account.",
    "I've cancelled the order and refunded $63.5 to your original payment method.",
    "I'm calling about order 2812, the mechanical keyboard hasn't arrived yet.",
    "Sure, it's ORD-2914.",
    "Yes, the order number is 2331.",
    "It's 1463, placed on 15/08.",
    "The confirmation number is 2183.",
    "Here it is: 1401.",
    "My account number is ACC-2363.",
    "The tracking number is TRK-1067.",
    "I placed it on 10/12, order 2677.",
    "I've applied a credit of $9.5 to your account.",
    "I've cancelled the order and refunded $60.0 to your original payment method.",
    "I'm calling about order 1060, the smartphone case is missing a part.",
    "Sure, it's ORD-1122.",
    "Yes, the order number is 2750.",
    "It's 1527, placed on 17/06.",
    "The confirmation number is 2600.",
    "Here it is: 2114.",
    "My account number is ACC-2001.",
    "The tracking number is TRK-1196.",
    "I placed it on 17/04, order 2406.",
    "I've applied a credit of $59.0 to your account.",
    "I've cancelled the order and refunded $20.5 to your original payment method.",
    "I'm calling about order 2803, the power bank keeps disconnecting.",
    "Sure, it's ORD-2359.",
    "Yes, the order number is 2224.",
    "It's 1132, placed on 10/09.",
    "The confirmation number is 2249.",
    "Here it is: 2032.",
    "My account number is ACC-1926.",
    "The tracking number is TRK-2171.",
    "I placed it on 12/09, order 2684.",
    "I've applied a credit of $64.5 to your account.",
    "I've cancelled the order and refunded $12.5 to your original payment method.",
    "I'm calling about order 1399, the office chair stopped working after a week.",
    "Sure, it's ORD-1573.",
    "Yes, the order number is 1091.",
    "It's 1068, placed on 02/12.",
    "The confirmation number is 1738.",
    "Here it is: 1987.",
    "My account number is ACC-1767.",
    "The tracking number is TRK-2749.",
    "I placed it on 14/01, order 2812.",
    "I've applied a credit of $55.5 to your account.",
    "I've cancelled the order and refunded $61.5 to your original payment method.",
    "Good afternoon, this is Jordan speaking, how can I help?",
    "Hello, I'm Taylor from customer support, what seems to be the issue?",
    "Thanks for calling, my name is Morgan, how can I help you today?",
    "I'm calling about order 2389, the vacuum cleaner won't charge.",
    "Sure, it's ORD-2066.",
    "Yes, the order number is 2353.",
    "It's 2246, placed on 04/03.",
    "The confirmation number is 2523.",
    "Here it is: 1855.",
    "My account number is ACC-2937.",
    "The tracking number is TRK-1183.",
    "I placed it on 06/05, order 1060.",
    "I've applied a credit of $59.5 to your account.",
    "I've cancelled the order and refunded $41.0 to your original payment method.",
    "Good afternoon, this is Wei speaking, how can I help?",
    "Hello, I'm Fatima from customer support, what seems to be the issue?",
    "Thanks for calling, my name is Diego, how can I help you today?",
    "I'm calling about order 2239, the desk lamp has a cracked screen.",
    "Sure, it's ORD-2797.",
    "Yes, the order number is 2231.",
    "It's 1251, placed on 18/06.",
    "The confirmation number is 1354.",
    "Here it is: 2959.",
    "My account number is ACC-2885.",
    "The tracking number is TRK-1874.",
    "I placed it on 04/06, order 2803.",
    "I've applied a credit of $24.5 to your account.",
    "I've cancelled the order and refunded $34.5 to your original payment method.",
    "I'm calling about order 2949, the air fryer makes a strange noise.",
    "Sure, it's ORD-1422.",
    "Yes, the order number is 1264.",
    "It's 1172, placed on 14/11.",
    "The confirmation number is 1315.",
    "Here it is: 1731.",
    "My account number is ACC-1253.",
    "The tracking number is TRK-1964.",
    "I placed it on 14/12, order 1399.",
    "I've applied a credit of $47.5 to your account.",
    "I've cancelled the order and refunded $52.0 to your original payment method.",
    "I'm calling about order 1547, the monitor stand arrived damaged.",
    "Sure, it's ORD-2479.",
    "Yes, the order number is 1297.",
    "It's 2332, placed on 21/10.",
    "The confirmation number is 2223.",
    "Here it is: 1730.",
    "My account number is ACC-2931.",
    "The tracking number is TRK-1652.",
    "I placed it on 22/09, order 2389.",
    "I've applied a credit of $26.0 to your account.",
    "I've cancelled the order and refunded $16.0 to your original payment method.",
    "I'm calling about order 2031, the bluetooth speaker won't turn on.",
    "Sure, it's ORD-2495.",
    "Yes, the order number is 1032.",
    "It's 2258, placed on 15/07.",
    "The confirmation number is 2832.",
    "Here it is: 2930.",
    "My account number is ACC-1291.",
    "The tracking number is TRK-2879.",
    "I placed it on 11/06, order 2239.",
    "I've applied a credit of $44.5 to your account.",
    "I've cancelled the order and refunded $45.0 to your original payment method.",
    "I'm calling about order 1368, the tablet is the wrong item.",
    "Sure, it's ORD-2623.",
    "Yes, the order number is 1971.",
    "It's 2275, placed on 07/05.",
    "The confirmation number is 2634.",
    "Here it is: 2291.",
    "My account number is ACC-2037.",
    "The tracking number is TRK-2545.",
    "I placed it on 23/09, order 2949.",
    "I've applied a credit of $65.5 to your account.",
    "I've cancelled the order and refunded $23.5 to your original payment method.",
    "I'm calling about order 2914, the desk lamp has a cracked screen.",
    "Sure, it's ORD-1426.",
    "Yes, the order number is 2419.",
    "It's 1708, placed on 14/09.",
    "The confirmation number is 1759.",
    "Here it is: 2904.",
    "My account number is ACC-1787.",
    "The tracking number is TRK-1187.",
    "I placed it on 24/10, order 1547.",
    "I've applied a credit of $11.5 to your account.",
    "I've cancelled the order and refunded $19.0 to your original payment method.",
    "I'm calling about order 1122, the air fryer makes a strange noise.",
    "Sure, it's ORD-2942.",
    "Yes, the order number is 1069.",
    "It's 1819, placed on 13/05.",
    "The confirmation number is 2163.",
    "Here it is: 2376.",
    "My account number is ACC-2580.",
    "The tracking number is TRK-1591.",
    "I placed it on 11/07, order 2031.",
    "I've applied a credit of $68.5 to your account.",
    "I've cancelled the order and refunded $36.5 to your original payment method.",
    "I'm calling about order 2359, the monitor stand arrived damaged.",
    "Sure, it's ORD-2331.",
    "Yes, the order number is 1463.",
    "It's 2183, placed on 21/04.",
    "The confirmation number is 1401.",
    "Here it is: 2363.",
    "My account number is ACC-1067.",
    "The tracking number is TRK-2677.",
    "I placed it on 22/01, order 1368.",
    "I've applied a credit of $37.5 to your account.",
    "I've cancelled the order and refunded $56.0 to your original payment method.",
    "I'm calling about order 1573, the bluetooth speaker won't turn on.",
    "Sure, it's ORD-2750.",
    "Yes, the order number is 1527.",
    "It's 2600, placed on 15/12.",
    "The confirmation number is 2114.",
    "Here it is: 2001.",
    "My account number is ACC-1196.",
    "The tracking number is TRK-2406.",
    "I placed it on 08/08, order 2914.",
    "I've applied a credit of $26.5 to your account.",
    "I've cancelled the order and refunded $11.0 to your original payment method.",
    "I'm calling about order 2066, the tablet is the wrong item.",
    "Sure, it's ORD-2224.",
    "Yes, the order number is 1132.",
    "It's 2249, placed on 23/01.",
    "The confirmation number is 2032.",
    "Here it is: 1926.",
    "My account number is ACC-2171.",
    "The tracking number is TRK-2684.",
    "I placed it on 01/10, order 1122.",
    "I've applied a credit of $34.0 to your account.",
    "I've cancelled the order and refunded $15.5 to your original payment method.",
    "Good afternoon, this is Fatima speaking, how can I help?",
    "Hello, I'm Diego from customer support, what seems to be the issue?",
    "Thanks for calling, my name is Elena, how can I help you today?",
    "I'm calling about order 2797, the desk lamp has a cracked screen.",
    "Sure, it's ORD-1091.",
    "Yes, the order number is 1068.",
    "It's 1738, placed on 19/05.",
    "The confirmation number is 1987.",
    "Here it is: 1767.",
    "My account number is ACC-2749.",
    "The tracking number is TRK-2812.",
    "I placed it on 13/08, order 2359.",
    "I've applied a credit of $46.0 to your account.",
    "I've cancelled the order and refunded $19.5 to your original payment method.",
    "Good afternoon, this is Taylor speaking, how can I help?",
    "Hello, I'm Morgan from customer support, what seems to be the issue?",
    "Thanks for calling, my name is Casey, how can I help you today?",
    "I'm calling about order 2100, the smartwatch stopped working after a week.",
    "Sure, it's ORD-2353.",
    "Yes, the order number is 2246.",
    "It's 2523, placed on 19/06.",
    "The confirmation number is 1855.",
    "Here it is: 2937.",
    "My account number is ACC-1183.",
    "The tracking number is TRK-1060.",
    "I placed it on 05/08, order 1573.",
    "I've applied a credit of $39.0 to your account.",
    "I've cancelled the order and refunded $64.0 to your original payment method.",
    "I'm calling about order 2479, the external hard drive won't charge.",
    "Sure, it's ORD-2231.",
    "Yes, the order number is 1251.",
    "It's 1354, placed on 21/12.",
    "The confirmation number is 2959.",
    "Here it is: 2885.",
    "My account number is ACC-1874.",
    "The tracking number is TRK-2803.",
    "I placed it on 19/08, order 2066.",
    "I've applied a credit of $38.5 to your account.",
    "I've cancelled the order and refunded $15.0 to your original payment method.",
    "I'm calling about order 2495, the wireless headphones hasn't arrived yet.",
    "Sure, it's ORD-2548.",
    "Yes, the order number is 2233.",
    "It's 2625, placed on 01/07.",
    "The confirmation number is 2475.",
    "Here it is: 1024.",
    "My account number is ACC-2175.",
    "The tracking number is TRK-1535.",
    "I placed it on 09/06, order 2695.",
    "I've applied a credit of $57.0 to your account.",
    "I've cancelled the order and refunded $67.5 to your original payment method.",
    "I'm calling about order 2623, the webcam is missing a part.",
    "Sure, it's ORD-1297.",
    "Yes, the order number is 2332.",
    "It's 2223, placed on 06/07.",
    "The confirmation number is 1730.",
    "Here it is: 2931.",
    "My account number is ACC-1652.",
    "The tracking number is TRK-1518.",
    "I placed it on 20/11, order 2100.",
    "I've applied a credit of $18.0 to your account.",
    "I've cancelled the order and refunded $10.0 to your original payment method.",
    "I'm calling about order 1426, the fitness tracker keeps disconnecting.",
    "Sure, it's ORD-1032.",
    "Yes, the order number is 2258.",
    "It's 2832, placed on 23/04.",
    "The confirmation number is 2930.",
    "Here it is: 1291.",
    "My account number is ACC-2879.",
    "The tracking number is TRK-2239.",
    "I placed it on 27/09, order 2479.",
    "I'm calling about order 2942, the smartwatch stopped working after a week.",
    "Sure, it's ORD-1971.",
    "Yes, the order number is 2275.",
    "It's 2634, placed on 07/03.",
    "The confirmation number is 2291.",
    "Here it is: 2037.",
    "My account number is ACC-2545.",
    "The tracking number is TRK-2949.",
    "I placed it on 25/01, order 2495.",
    "I'm calling about order 2331, the external hard drive won't charge.",
    "Sure, it's ORD-2419.",
    "Yes, the order number is 1708.",
    "It's 1759, placed on 15/01.",
    "The confirmation number is 2904.",
    "Here it is: 1787.",
    "My account number is ACC-1187.",
    "The tracking number is TRK-1547.",
    "I placed it on 12/10, order 2623.",
    "I'm calling about order 2750, the wireless headphones hasn't arrived yet.",
    "Sure, it's ORD-1069.",
    "Yes, the order number is 1819.",
    "It's 2163, placed on 20/12.",
    "The confirmation number is 2376.",
    "Here it is: 2580.",
    "My account number is ACC-1591.",
    "The tracking number is TRK-2031.",
    "I placed it on 13/10, order 1426.",
    "I'm calling about order 2224, the webcam is missing a part.",
    "Sure, it's ORD-1463.",
    "Yes, the order number is 2183.",
    "It's 1401, placed on 01/12.",
    "The confirmation number is 2363.",
    "Here it is: 1067.",
    "My account number is ACC-2677.",
    "The tracking number is TRK-1368.",
    "I placed it on 05/12, order 2942.",
    "Good afternoon, this is Diego speaking, how can I help?",
    "Hello, I'm Elena from customer support, what seems to be the issue?",
    "I'm calling about order 1091, the fitness tracker keeps disconnecting.",
    "Sure, it's ORD-1527.",
    "Yes, the order number is 2600.",
    "It's 2114, placed on 05/05.",
    "The confirmation number is 2001.",
    "Here it is: 1196.",
    "My account number is ACC-2406.",
    "The tracking number is TRK-2914.",
    "I placed it on 05/03, order 2331.",
    "I've applied a credit of $55.0 to your account.",
    "I'm calling about order 2688, the router won't turn on.",
    "Sure, it's ORD-1132.",
    "Yes, the order number is 2249.",
    "It's 2032, placed on 16/10.",
    "The confirmation number is 1926.",
    "Here it is: 2171.",
    "My account number is ACC-2684.",
    "The tracking number is TRK-1122.",
    "I placed it on 10/11, order 2750.",
    "I've applied a credit of $28.0 to your account.",
    "I've cancelled the order and refunded $18.5 to your original payment method.",
    "Thanks for calling, my name is Noah, how can I help you today?",
    "I'm calling about order 2802, the coffee maker is the wrong item.",
    "Sure, it's ORD-1068.",
    "Yes, the order number is 1738.",
    "It's 1987, placed on 12/07.",
    "The confirmation number is 1767.",
    "Here it is: 2749.",
    "My account number is ACC-2812.",
    "The tracking number is TRK-2359.",
    "I placed it on 08/04, order 2224.",
    "I've applied a credit of $30.0 to your account.",
    "I've cancelled the order and refunded $25.0 to your original payment method.",
    "I'm calling about order 2548, the printer has a cracked screen.",
    "Sure, it's ORD-2579.",
    "Yes, the order number is 1156.",
    "It's 1855, placed on 09/12.",
    "The confirmation number is 2937.",
    "Here it is: 1183.",
    "My account number is ACC-1060.",
    "The tracking number is TRK-1573.",
    "I placed it on 18/08, order 1091.",
    "I've applied a credit of $42.0 to your account.",
    "I've cancelled the order and refunded $58.0 to your original payment method.",
    "I'm calling about order 1297, the gaming mouse makes a strange noise.",
    "Sure, it's ORD-2808.",
    "Yes, the order number is 2977.",
    "It's 2109, placed on 22/10.",
    "The confirmation number is 1800.",
    "Here it is: 2503.",
    "My account number is ACC-2658.",
    "The tracking number is TRK-2627.",
    "I placed it on 10/08, order 2688.",
    "I've applied a credit of $41.5 to your account.",
    "I've cancelled the order and refunded $10.5 to your original payment method.",
    "I'm calling about order 1032, the laptop charger arrived damaged.",
    "Sure, it's ORD-2233.",
    "Yes, the order number is 2625.",
    "It's 2475, placed on 03/06.",
    "The confirmation number is 1024.",
    "Here it is: 2175.",
    "My account number is ACC-1535.",
    "The tracking number is TRK-2695.",
    "I placed it on 16/02, order 2802.",
    "I've applied a credit of $27.5 to your account.",
    "I've cancelled the order and refunded $32.0 to your original payment method.",
    "I'm calling about order 1971, the router won't turn on.",
    "Sure, it's ORD-2332.",
    "Yes, the order number is 2223.",
    "It's 1730, placed on 06/08.",
    "The confirmation number is 2931.",
    "Here it is: 1652.",
    "My account number is ACC-1518.",
    "The tracking number is TRK-2100.",
    "I placed it on 23/02, order 2548.",
    "I'm calling about order 2419, the coffee maker is the wrong item.",
    "Sure, it's ORD-2258.",
    "Yes, the order number is 2832.",
    "It's 2930, placed on 27/02.",
    "The confirmation number is 1291.",
    "Here it is: 2879.",
    "My account number is ACC-2239.",
    "The tracking number is TRK-2479.",
    "I placed it on 05/07, order 1297.",
    "I'm calling about order 1069, the printer has a cracked screen.",
    "Sure, it's ORD-2275.",
    "Yes, the order number is 2634.",
    "It's 2291, placed on 02/05.",
    "The confirmation number is 2037.",
    "Here it is: 2545.",
    "My account number is ACC-2949.",
    "The tracking number is TRK-2495.",
    "I placed it on 04/09, order 1032.",
    "I'm calling about order 1463, the gaming mouse makes a strange noise.",
    "Sure, it's ORD-1708.",
    "Yes, the order number is 1759.",
    "It's 2904, placed on 15/11.",
    "The confirmation number is 1787.",
    "Here it is: 1187.",
    "My account number is ACC-1547.",
    "The tracking number is TRK-2623.",
    "I placed it on 17/01, order 1971.",
    "I'm calling about order 1527, the laptop charger arrived damaged.",
    "Sure, it's ORD-1819.",
    "Yes, the order number is 2163.",
    "It's 2376, placed on 20/01.",
    "The confirmation number is 2580.",
    "Here it is: 1591.",
    "My account number is ACC-2031.",
    "The tracking number is TRK-1426.",
    "I placed it on 26/09, order 2419.",
    "I'm calling about order 1132, the router won't turn on.",
    "Sure, it's ORD-2183.",
    "Yes, the order number is 1401.",
    "It's 2363, placed on 28/09.",
    "The confirmation number is 1067.",
    "Here it is: 2677.",
    "My account number is ACC-1368.",
    "The tracking number is TRK-2942.",
    "I placed it on 26/10, order 1069.",
    "I've applied a credit of $60.0 to your account.",
    "I've cancelled the order and refunded $38.0 to your original payment method.",
    "I'm calling about order 1955, the smartphone case is missing a part.",
    "Sure, it's ORD-2600.",
    "Yes, the order number is 2114.",
    "It's 2001, placed on 13/09.",
    "The confirmation number is 1196.",
    "Here it is: 2406.",
    "My account number is ACC-2914.",
    "The tracking number is TRK-2331.",
    "I placed it on 15/08, order 1463.",
    "I've applied a credit of $20.5 to your account.",
    "I've cancelled the order and refunded $50.0 to your original payment method.",
    "I'm calling about order 2579, the power bank keeps disconnecting.",
    "Sure, it's ORD-2249.",
    "Yes, the order number is 2032.",
    "It's 1926, placed on 19/10.",
    "The confirmation number is 2171.",
    "Here it is: 2684.",
    "My account number is ACC-1122.",
    "The tracking number is TRK-2750.",
    "I placed it on 17/06, order 1527.",
    "I've applied a credit of $12.5 to your account.",
    "I've cancelled the order and refunded $62.0 to your original payment method.",
    "I'm calling about order 2808, the office chair stopped working after a week.",
    "Sure, it's ORD-2368.",
    "Yes, the order number is 2910.",
    "It's 1304, placed on 24/02.",
    "The confirmation number is 1182.",
    "Here it is: 2812.",
    "My account number is ACC-2359.",
    "The tracking number is TRK-2224.",
    "I placed it on 10/09, order 1132.",
    "I've applied a credit of $61.5 to your account.",
    "I've cancelled the order and refunded $36.0 to your original payment method.",
    "I'm calling about order 2233, the vacuum cleaner won't charge.",
    "Sure, it's ORD-1156.",
    "Yes, the order number is 1545.",
    "It's 2515, placed on 18/05.",
    "The confirmation number is 1265.",
    "Here it is: 2883.",
    "My account number is ACC-2207.",
    "The tracking number is TRK-2651.",
    "I placed it on 14/10, order 1955.",
    "I've applied a credit of $41.0 to your account.",
    "I've cancelled the order and refunded $21.5 to your original payment method.",
    "I'm calling about order 2332, the mechanical keyboard hasn't arrived yet.",
    "Sure, it's ORD-2977.",
    "Yes, the order number is 2109.",
    "It's 1800, placed on 17/09.",
    "The confirmation number is 2503.",
    "Here it is: 2658.",
    "My account number is ACC-2627.",
    "The tracking number is TRK-2688.",
    "I placed it on 28/05, order 2579.",
    "I've applied a credit of $34.5 to your account.",
    "I've cancelled the order and refunded $60.5 to your original payment method.",
    "I'm calling about order 2258, the smartphone case is missing a part.",
    "Sure, it's ORD-2625.",
    "Yes, the order number is 2475.",
    "It's 1024, placed on 22/05.",
    "The confirmation number is 2175.",
    "Here it is: 1535.",
    "My account number is ACC-2695.",
    "The tracking number is TRK-2802.",
    "I placed it on 12/04, order 2808.",
    "I'm calling about order 2275, the power bank keeps disconnecting.",
    "Sure, it's ORD-2223.",
    "Yes, the order number is 1730.",
    "It's 2931, placed on 03/07.",
    "The confirmation number is 1652.",
    "Here it is: 1518.",
    "My account number is ACC-2100.",
    "The tracking number is TRK-2548.",
    "I placed it on 24/05, order 2233.",
    "I'm calling about order 1708, the office chair stopped working after a week.",
    "Sure, it's ORD-2832.",
    "Yes, the order number is 2930.",
    "It's 1291, placed on 03/08.",
    "The confirmation number is 2879.",
    "Here it is: 2239.",
    "My account number is ACC-2479.",
    "The tracking number is TRK-1297.",
    "I placed it on 21/10, order 2332.",
    "I'm calling about order 1819, the vacuum cleaner won't charge.",
    "Sure, it's ORD-2634.",
    "Yes, the order number is 2291.",
    "It's 2037, placed on 08/05.",
    "The confirmation number is 2545.",
    "Here it is: 2949.",
    "My account number is ACC-2495.",
    "The tracking number is TRK-1032.",
    "I placed it on 15/07, order 2258.",
    "I'm calling about order 2183, the mechanical keyboard hasn't arrived yet.",
    "Sure, it's ORD-1759.",
    "Yes, the order number is 2904.",
    "It's 1787, placed on 05/10.",
    "The confirmation number is 1187.",
    "Here it is: 1547.",
    "My account number is ACC-2623.",
    "The tracking number is TRK-1971.",
    "I placed it on 07/05, order 2275.",
    "I'm calling about order 2600, the smartphone case is missing a part.",
    "Sure, it's ORD-2163.",
    "Yes, the order number is 2376.",
    "It's 2580, placed on 01/04.",
    "The confirmation number is 1591.",
    "Here it is: 2031.",
    "My account number is ACC-1426.",
    "The tracking number is TRK-2419.",
    "I placed it on 14/09, order 1708.",
    "I've applied a credit of $36.5 to your account.",
    "I've cancelled the order and refunded $62.5 to your original payment method.",
    "I'm calling about order 2063, the monitor stand arrived damaged.",
    "Sure, it's ORD-1401.",
    "Yes, the order number is 2363.",
    "It's 1067, placed on 12/05.",
    "The confirmation number is 2677.",
    "Here it is: 1368.",
    "My account number is ACC-2942.",
    "The tracking number is TRK-1069.",
    "I placed it on 13/05, order 1819.",
    "I've applied a credit of $56.0 to your account.",
    "I've cancelled the order and refunded $65.0 to your original payment method.",
    "I'm calling about order 2368, the bluetooth speaker won't turn on.",
    "Sure, it's ORD-2114.",
    "Yes, the order number is 2001.",
    "It's 1196, placed on 06/02.",
    "The confirmation number is 2406.",
    "Here it is: 2914.",
    "My account number is ACC-2331.",
    "The tracking number is TRK-1463.",
    "I placed it on 21/04, order 2183.",
    "I've applied a credit of $11.0 to your account.",
    "I've cancelled the order and refunded $52.5 to your original payment method.",
    "I'm calling about order 1156, the tablet is the wrong item.",
    "Sure, it's ORD-1813.",
    "Yes, the order number is 1121.",
    "It's 2044, placed on 25/09.",
    "The confirmation number is 1712.",
    "Here it is: 2965.",
    "My account number is ACC-1578.",
    "The tracking number is TRK-1527.",
    "I placed it on 15/12, order 2600.",
    "I've applied a credit of $15.5 to your account.",
    "I've cancelled the order and refunded $16.5 to your original payment method.",
    "I'm calling about order 2977, the desk lamp has a cracked screen.",
    "Sure, it's ORD-2910.",
    "Yes, the order number is 1304.",
    "It's 1182, placed on 27/11.",
    "The confirmation number is 1288.",
    "Here it is: 1358.",
    "My account number is ACC-1199.",
    "The tracking number is TRK-1461.",
    "I placed it on 01/08, order 2063.",
    "I've applied a credit of $19.5 to your account.",
    "I've cancelled the order and refunded $48.5 to your original payment method.",
    "I'm calling about order 2625, the air fryer makes a strange noise.",
    "Sure, it's ORD-1545.",
    "Yes, the order number is 2515.",
    "It's 1265, placed on 13/02.",
    "The confirmation number is 2883.",
    "Here it is: 2207.",
    "My account number is ACC-2651.",
    "The tracking number is TRK-1955.",
    "I placed it on 06/01, order 2368.",
    "I've cancelled the order and refunded $29.5 to your original payment method.",
    "I'm calling about order 2223, the monitor stand arrived damaged.",
    "Sure, it's ORD-2109.",
    "Yes, the order number is 1800.",
    "It's 2503, placed on 18/09.",
    "The confirmation number is 2658.",
    "Here it is: 2627.",
    "My account number is ACC-2688.",
    "The tracking number is TRK-2579.",
    "I placed it on 04/04, order 1156.",
    "I'm calling about order 2832, the bluetooth speaker won't turn on.",
    "Sure, it's ORD-2475.",
    "Yes, the order number is 1024.",
    "It's 2175, placed on 06/12.",
    "The confirmation number is 1535.",
    "Here it is: 2695.",
    "My account number is ACC-2802.",
    "The tracking number is TRK-2808.",
    "I placed it on 03/12, order 2977.",
    "I'm calling about order 2634, the tablet is the wrong item.",
    "Sure, it's ORD-1730.",
    "Yes, the order number is 2931.",
    "It's 1652, placed on 12/12.",
    "The confirmation number is 1518.",
    "Here it is: 2100.",
    "My account number is ACC-2548.",
    "The tracking number is TRK-2233.",
    "I placed it on 01/07, order 2625.",
    "I'm calling about order 1759, the desk lamp has a cracked screen.",
    "Sure, it's ORD-2930.",
    "Yes, the order number is 1291.",
    "It's 2879, placed on 05/04.",
    "The confirmation number is 2239.",
    "Here it is: 2479.",
    "My account number is ACC-1297.",
    "The tracking number is TRK-2332.",
    "I placed it on 06/07, order 2223.",
    "I'm calling about order 2163, the air fryer makes a strange noise.",
    "Sure, it's ORD-2291.",
    "Yes, the order number is 2037.",
    "It's 2545, placed on 07/10.",
    "The confirmation number is 2949.",
    "Here it is: 2495.",
    "My account number is ACC-1032.",
    "The tracking number is TRK-2258.",
    "I placed it on 23/04, order 2832.",
    "I'm calling about order 1401, the monitor stand arrived damaged.",
    "Sure, it's ORD-2904.",
    "Yes, the order number is 1787.",
    "It's 1187, placed on 11/11.",
    "The confirmation number is 1547.",
    "Here it is: 2623.",
    "My account number is ACC-1971.",
    "The tracking number is TRK-2275.",
    "I placed it on 07/03, order 2634.",
    "I've applied a credit of $31.5 to your account.",
    "I've cancelled the order and refunded $33.0 to your original payment method.",
    "I'm calling about order 1361, the wireless headphones hasn't arrived yet.",
    "Sure, it's ORD-2376.",
    "Yes, the order number is 2580.",
    "It's 1591, placed on 26/07.",
    "The confirmation number is 2031.",
    "Here it is: 1426.",
    "My account number is ACC-2419.",
    "The tracking number is TRK-1708.",
    "I placed it on 15/01, order 1759.",
    "I've applied a credit of $44.0 to your account.",
    "I've cancelled the order and refunded $14.5 to your original payment method.",
    "I'm calling about order 1813, the webcam is missing a part.",
    "Sure, it's ORD-2363.",
    "Yes, the order number is 1067.",
    "It's 2677, placed on 10/12.",
    "The confirmation number is 1368.",
    "Here it is: 2942.",
    "My account number is ACC-1069.",
    "The tracking number is TRK-1819.",
    "I placed it on 20/12, order 2163.",
    "I've applied a credit of $17.0 to your account.",
    "I've cancelled the order and refunded $40.5 to your original payment method.",
    "I'm calling about order 2910, the fitness tracker keeps disconnecting.",
    "Sure, it's ORD-2286.",
    "Yes, the order number is 2170.",
    "It's 1908, placed on 14/08.",
    "The confirmation number is 1458.",
    "Here it is: 1098.",
    "My account number is ACC-2434.",
    "The tracking number is TRK-2638.",
    "I placed it on 24/01, order 1736.",
    "I've applied a credit of $48.0 to your account.",
    "I've cancelled the order and refunded $9.5 to your original payment method.",
    "I'm calling about order 1545, the smartwatch stopped working after a week.",
    "Sure, it's ORD-1121.",
    "Yes, the order number is 2044.",
    "It's 1712, placed on 11/12.",
    "The confirmation number is 2965.",
    "Here it is: 1578.",
    "My account number is ACC-1713.",
    "The tracking number is TRK-2966.",
    "I placed it on 02/08, order 1361.",
    "I've applied a credit of $18.5 to your account.",
    "I've cancelled the order and refunded $59.0 to your original payment method.",
    "I'm calling about order 2109, the external hard drive won't charge.",
    "Sure, it's ORD-1304.",
    "Yes, the order number is 1182.",
    "It's 1288, placed on 21/11.",
    "The confirmation number is 1358.",
    "Here it is: 1199.",
    "My account number is ACC-1461.",
    "The tracking number is TRK-2063.",
    "I placed it on 04/05, order 1813.",
    "I'm calling about order 2475, the wireless headphones hasn't arrived yet.",
    "Sure, it's ORD-2515.",
    "Yes, the order number is 1265.",
    "It's 2883, placed on 21/08.",
    "The confirmation number is 2207.",
    "Here it is: 2651.",
    "My account number is ACC-1955.",
    "The tracking number is TRK-2368.",
    "I placed it on 02/06, order 2910.",
    "I'm calling about order 1730, the webcam is missing a part.",
    "Sure, it's ORD-1800.",
    "Yes, the order number is 2503.",
    "It's 2658, placed on 26/12.",
    "The confirmation number is 2627.",
    "Here it is: 2688.",
    "My account number is ACC-2579.",
    "The tracking number is TRK-1156.",
    "I placed it on 19/02, order 1545.",
    "I'm calling about order 2930, the fitness tracker keeps disconnecting.",
    "Sure, it's ORD-1024.",
    "Yes, the order number is 2175.",
    "It's 1535, placed on 07/09.",
    "The confirmation number is 2695.",
    "Here it is: 2802.",
    "My account number is ACC-2808.",
    "The tracking number is TRK-2977.",
    "I placed it on 22/10, order 2109.",
    "I'm calling about order 2291, the smartwatch stopped working after a week.",
    "Sure, it's ORD-2931.",
    "Yes, the order number is 1652.",
    "It's 1518, placed on 09/04.",
    "The confirmation number is 2100.",
    "Here it is: 2548.",
    "My account number is ACC-2233.",
    "The tracking number is TRK-2625.",
    "I placed it on 03/06, order 2475.",
    "I'm calling about order 2904, the external hard drive won't charge.",
    "Sure, it's ORD-1291.",
    "Yes, the order number is 2879.",
    "It's 2239, placed on 11/06.",
    "The confirmation number is 2479.",
    "Here it is: 1297.",
    "My account number is ACC-2332.",
    "The tracking number is TRK-2223.",
    "I placed it on 06/08, order 1730.",
    "I've applied a credit of $21.0 to your account.",
    "I'm calling about order 2376, the wireless headphones hasn't arrived yet.",
    "Sure, it's ORD-2037.",
    "Yes, the order number is 2545.",
    "It's 2949, placed on 23/09.",
    "The confirmation number is 2495.",
    "Here it is: 1032.",
    "My account number is ACC-2258.",
    "The tracking number is TRK-2832.",
    "I placed it on 27/02, order 2930.",
    "I've applied a credit of $66.5 to your account.",
    "I've cancelled the order and refunded $68.0 to your original payment method.",
    "I'm calling about order 2501, the gaming mouse makes a strange noise.",
    "Sure, it's ORD-1787.",
    "Yes, the order number is 1187.",
    "It's 1547, placed on 24/10.",
    "The confirmation number is 2623.",
    "Here it is: 1971.",
    "My account number is ACC-2275.",
    "The tracking number is TRK-2634.",
    "I placed it on 02/05, order 2291.",
    "I've applied a credit of $24.0 to your account.",
    "I've cancelled the order and refunded $65.5 to your original payment method.",
    "I'm calling about order 2286, the laptop charger arrived damaged.",
    "Sure, it's ORD-1729.",
    "Yes, the order number is 1591.",
    "It's 2031, placed on 11/07.",
    "The confirmation number is 1426.",
    "Here it is: 2419.",
    "My account number is ACC-1708.",
    "The tracking number is TRK-1759.",
    "I placed it on 15/11, order 2904.",
    "I've applied a credit of $22.5 to your account.",
    "I've cancelled the order and refunded $11.5 to your original payment method.",
    "I'm calling about order 1121, the router won't turn on.",
    "Sure, it's ORD-2294.",
    "Yes, the order number is 2736.",
    "It's 1842, placed on 10/06.",
    "The confirmation number is 1344.",
    "Here it is: 2341.",
    "My account number is ACC-2881.",
    "The tracking number is TRK-1718.",
    "I placed it on 20/03, order 2401.",
    "I've applied a credit of $38.0 to your account.",
    "I've cancelled the order and refunded $68.5 to your original payment method.",
    "I'm calling about order 1304, the coffee maker is the wrong item.",
    "Sure, it's ORD-2170.",
    "Yes, the order number is 1908.",
    "It's 1458, placed on 06/11.",
    "The confirmation number is 1098.",
    "Here it is: 2434.",
    "My account number is ACC-2638.",
    "The tracking number is TRK-1736.",
    "I placed it on 26/02, order 2501.",
    "I've applied a credit of $50.0 to your account.",
    "I've cancelled the order and refunded $37.5 to your original payment method.",
    "I'm calling about order 2515, the printer has a cracked screen.",
    "Sure, it's ORD-2044.",
    "Yes, the order number is 1712.",
    "It's 2965, placed on 24/09.",
    "The confirmation number is 1578.",
    "Here it is: 1713.",
    "My account number is ACC-2966.",
    "The tracking number is TRK-1361.",
    "I placed it on 02/03, order 2286.",
    "I'm calling about order 1800, the gaming mouse makes a strange noise.",
    "Sure, it's ORD-1182.",
    "Yes, the order number is 1288.",
    "It's 1358, placed on 17/02.",
    "The confirmation number is 1199.",
    "Here it is: 1461.",
    "My account number is ACC-2063.",
    "The tracking number is TRK-1813.",
    "I placed it on 26/03, order 1121.",
    "I'm calling about order 1024, the laptop charger arrived damaged.",
    "Sure, it's ORD-1265.",
    "Yes, the order number is 2883.",
    "It's 2207, placed on 08/09.",
    "The confirmation number is 2651.",
    "Here it is: 1955.",
    "My account number is ACC-2368.",
    "The tracking number is TRK-2910.",
    "I placed it on 24/02, order 1304.",
    "I'm calling about order 2931, the router won't turn on.",
    "Sure, it's ORD-2503.",
    "Yes, the order number is 2658.",
    "It's 2627, placed on 21/02.",
    "The confirmation number is 2688.",
    "Here it is: 2579.",
    "My account number is ACC-1156.",
    "The tracking number is TRK-1545.",
    "I placed it on 18/05, order 2515.",
    "I'm calling about order 1291, the coffee maker is the wrong item.",
    "Sure, it's ORD-2175.",
    "Yes, the order number is 1535.",
    "It's 2695, placed on 09/06.",
    "The confirmation number is 2802.",
    "Here it is: 2808.",
    "My account number is ACC-2977.",
    "The tracking number is TRK-2109.",
    "I placed it on 17/09, order 1800.",
    "I'm calling about order 2037, the printer has a cracked screen.",
    "Sure, it's ORD-1652.",
    "Yes, the order number is 1518.",
    "It's 2100, placed on 20/11.",
    "The confirmation number is 2548.",
    "Here it is: 2233.",
    "My account number is ACC-2625.",
    "The tracking number is TRK-2475.",
    "I placed it on 22/05, order 1024.",
    "I've applied a credit of $53.0 to your account.",
    "I'm calling about order 1666, the office chair stopped working after a week.",
    "Sure, it's ORD-2879.",
    "Yes, the order number is 2239.",
    "It's 2479, placed on 27/09.",
    "The confirmation number is 1297.",
    "Here it is: 2332.",
    "My account number is ACC-2223.",
    "The tracking number is TRK-1730.",
    "I placed it on 03/07, order 2931.",
    "I've applied a credit of $22.0 to your account.",
    "I've cancelled the order and refunded $13.0 to your original payment method.",
    "I'm calling about order 1729, the vacuum cleaner won't charge.",
    "Sure, it's ORD-2545.",
    "Yes, the order number is 2949.",
    "It's 2495, placed on 25/01.",
    "The confirmation number is 1032.",
    "Here it is: 2258.",
    "My account number is ACC-2832.",
    "The tracking number is TRK-2930.",
    "I placed it on 03/08, order 1291.",
    "I've applied a credit of $40.0 to your account.",
    "I've cancelled the order and refunded $50.5 to your original payment method.",
    "I'm calling about order 2294, the mechanical keyboard hasn't arrived yet.",
    "Sure, it's ORD-1630.",
    "Yes, the order number is 1751.",
    "It's 1274, placed on 18/07.",
    "The confirmation number is 1971.",
    "Here it is: 2275.",
    "My account number is ACC-2634.",
    "The tracking number is TRK-2291.",
    "I placed it on 08/05, order 2037.",
    "I've applied a credit of $54.0 to your account.",
    "I've cancelled the order and refunded $67.0 to your original payment method.",
    "I'm calling about order 2170, the smartphone case is missing a part.",
    "Sure, it's ORD-1357.",
    "Yes, the order number is 1018.",
    "It's 2656, placed on 22/07.",
    "The confirmation number is 2392.",
    "Here it is: 2633.",
    "My account number is ACC-1671.",
    "The tracking number is TRK-2303.",
    "I placed it on 07/04, order 1666.",
    "I've applied a credit of $62.5 to your account.",
    "I've cancelled the order and refunded $17.5 to your original payment method.",
    "I'm calling about order 2044, the power bank keeps disconnecting.",
    "Sure, it's ORD-2736.",
    "Yes, the order number is 1842.",
    "It's 1344, placed on 25/04.",
    "The confirmation number is 2341.",
    "Here it is: 2881.",
    "My account number is ACC-1718.",
    "The tracking number is TRK-2401.",
    "I placed it on 10/07, order 1729.",
    "I've applied a credit of $65.0 to your account.",
    "I've cancelled the order and refunded $66.0 to your original payment method.",
    "I'm calling about order 1182, the office chair stopped working after a week.",
    "Sure, it's ORD-1908.",
    "Yes, the order number is 1458.",
    "It's 1098, placed on 22/03.",
    "The confirmation number is 2434.",
    "Here it is: 2638.",
    "My account number is ACC-1736.",
    "The tracking number is TRK-2501.",
    "I placed it on 19/03, order 2294.",
    "I'm calling about order 1265, the vacuum cleaner won't charge.",
    "Sure, it's ORD-1712.",
    "Yes, the order number is 2965.",
    "It's 1578, placed on 23/10.",
    "The confirmation number is 1713.",
    "Here it is: 2966.",
    "My account number is ACC-1361.",
    "The tracking number is TRK-2286.",
    "I placed it on 17/11, order 2170.",
    "I'm calling about order 2503, the mechanical keyboard hasn't arrived yet.",
    "Sure, it's ORD-1288.",
    "Yes, the order number is 1358.",
    "It's 1199, placed on 13/12.",
    "The confirmation number is 1461.",
    "Here it is: 2063.",
    "My account number is ACC-1813.",
    "The tracking number is TRK-1121.",
    "I placed it on 25/09, order 2044.",
    "I'm calling about order 2175, the smartphone case is missing a part.",
    "Sure, it's ORD-2883.",
    "Yes, the order number is 2207.",
    "It's 2651, placed on 17/05.",
    "The confirmation number is 1955.",
    "Here it is: 2368.",
    "My account number is ACC-2910.",
    "The tracking number is TRK-1304.",
    "I placed it on 27/11, order 1182.",
    "I'm calling about order 1652, the power bank keeps disconnecting.",
    "Sure, it's ORD-2658.",
    "Yes, the order number is 2627.",
    "It's 2688, placed on 10/08.",
    "The confirmation number is 2579.",
    "Here it is: 1156.",
    "My account number is ACC-1545.",
    "The tracking number is TRK-2515.",
    "I placed it on 13/02, order 1265.",
    "I'm calling about order 2879, the office chair stopped working after a week.",
    "Sure, it's ORD-1535.",
    "Yes, the order number is 2695.",
    "It's 2802, placed on 16/02.",
    "The confirmation number is 2808.",
    "Here it is: 2977.",
    "My account number is ACC-2109.",
    "The tracking number is TRK-1800.",
    "I placed it on 18/09, order 2503.",
    "I've applied a credit of $61.0 to your account.",
    "I've cancelled the order and refunded $12.0 to your original payment method.",
    "I'm calling about order 1252, the tablet is the wrong item.",
    "Sure, it's ORD-1518.",
    "Yes, the order number is 2100.",
    "It's 2548, placed on 23/02.",
    "The confirmation number is 2233.",
    "Here it is: 2625.",
    "My account number is ACC-2475.",
    "The tracking number is TRK-1024.",
    "I placed it on 06/12, order 2175.",
    "I've applied a credit of $27.0 to your account.",
    "I've cancelled the order and refunded $25.5 to your original payment method.",
    "I'm calling about order 1630, the desk lamp has a cracked screen.",
    "Sure, it's ORD-2239.",
    "Yes, the order number is 2479.",
    "It's 1297, placed on 05/07.",
    "The confirmation number is 2332.",
    "Here it is: 2223.",
    "My account number is ACC-1730.",
    "The tracking number is TRK-2931.",
    "I placed it on 12/12, order 1652.",
    "I've applied a credit of $43.0 to your account.",
    "I've cancelled the order and refunded $47.0 to your original payment method.",
    "I'm calling about order 1357, the air fryer makes a strange noise.",
    "Sure, it's ORD-2616.",
    "Yes, the order number is 1993.",
    "It's 1363, placed on 12/01.",
    "The confirmation number is 1872.",
    "Here it is: 2028.",
    "My account number is ACC-2930.",
    "The tracking number is TRK-1291.",
    "I placed it on 05/04, order 2879.",
    "I've applied a credit of $28.5 to your account.",
    "I've cancelled the order and refunded $58.5 to your original payment method.",
    "I'm calling about order 2736, the monitor stand arrived damaged.",
    "Sure, it's ORD-1751.",
    "Yes, the order number is 1274.",
    "It's 1636, placed on 13/11.",
    "The confirmation number is 1017.",
    "Here it is: 2559.",
    "My account number is ACC-1486.",
    "The tracking number is TRK-2315.",
    "I placed it on 23/07, order 1252.",
    "I've applied a credit of $33.0 to your account.",
    "I've cancelled the order and refunded $30.5 to your original payment method.",
    "I'm calling about order 1908, the bluetooth speaker won't turn on.",
    "Sure, it's ORD-1018.",
    "Yes, the order number is 2656.",
    "It's 2392, placed on 07/12.",
    "The confirmation number is 2633.",
    "Here it is: 1671.",
    "My account number is ACC-2303.",
    "The tracking number is TRK-1666.",
    "I placed it on 22/06, order 1630.",
    "I've cancelled the order and refunded $49.5 to your original payment method.",
    "I'm calling about order 1712, the tablet is the wrong item.",
    "Sure, it's ORD-1842.",
    "Yes, the order number is 1344.",
    "It's 2341, placed on 04/07.",
    "The confirmation number is 2881.",
    "Here it is: 1718.",
    "My account number is ACC-2401.",
    "The tracking number is TRK-1729.",
    "I placed it on 07/07, order 1357.",
    "I'm calling about order 1288, the desk lamp has a cracked screen.",
    "Sure, it's ORD-1458.",
    "Yes, the order number is 1098.",
    "It's 2434, placed on 14/02.",
    "The confirmation number is 2638.",
    "Here it is: 1736.",
    "My account number is ACC-2501.",
    "The tracking number is TRK-2294.",
    "I placed it on 24/07, order 2736.",
    "I'm calling about order 2883, the air fryer makes a strange noise.",
    "Sure, it's ORD-2965.",
    "Yes, the order number is 1578.",
    "It's 1713, placed on 23/03.",
    "The confirmation number is 2966.",
    "Here it is: 1361.",
    "My account number is ACC-2286.",
    "The tracking number is TRK-2170.",
    "I placed it on 14/08, order 1908.",
    "I'm calling about order 2658, the monitor stand arrived damaged.",
    "Sure, it's ORD-1358.",
    "Yes, the order number is 1199.",
    "It's 1461, placed on 04/01.",
    "The confirmation number is 2063.",
    "Here it is: 1813.",
    "My account number is ACC-1121.",
    "The tracking number is TRK-2044.",
    "I placed it on 11/12, order 1712.",
    "I'm calling about order 1535, the bluetooth speaker won't turn on.",
    "Sure, it's ORD-2207.",
    "Yes, the order number is 2651.",
    "It's 1955, placed on 14/10.",
    "The confirmation number is 2368.",
    "Here it is: 2910.",
    "My account number is ACC-1304.",
    "The tracking number is TRK-1182.",
    "I placed it on 21/11, order 1288.",
    "I'm calling about order 1518, the tablet is the wrong item.",
    "Sure, it's ORD-2627.",
    "Yes, the order number is 2688.",
    "It's 2579, placed on 28/05.",
    "The confirmation number is 1156.",
    "Here it is: 1545.",
    "My account number is ACC-2515.",
    "The tracking number is TRK-1265.",
    "I placed it on 21/08, order 2883.",
    "I've applied a credit of $37.0 to your account.",
    "I've cancelled the order and refunded $43.5 to your original payment method.",
    "I'm calling about order 1782, the fitness tracker keeps disconnecting.",
    "Sure, it's ORD-2695.",
    "Yes, the order number is 2802.",
    "It's 2808, placed on 12/04.",
]
